--- 
title: "Making Sense of Crime Data"
author: 
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    includes:
      in_header: header.html
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a companion workbook for the 2nd year undergraduate module CRIM20441 Making Sense of Criminological Data at the University of Manchester."
---

# Introduction {-}

This study material is designed to introduce Criminology students at the University of Manchester to using data analysis in crime research and practice. These teaching materials were originally developed by Reka Solymosi and are currently being updated and maintained by Ana Nicoriciu and Sam Langton.

These lab notes are a work in progress. If you have any suggestions or find any errors, please don’t hesitate to contact us. We appreciate your feedback and will use it to improve the material for future students.

This workbook contains the lab materials for an introduction to a data analysis course designed for **CRIM20441 Making Sense of Criminological Data**, a 2nd-year undergraduate module of the BA Criminology programme at the University of Manchester.

Throughout this course unit, you'll explore the essential techniques of descriptive data analysis in criminology, integrating both quantitative and qualitative approaches. Quantitative methods provide structured ways to measure and analyse crime data patterns, while qualitative methods offer a deeper understanding of the meanings and contexts behind those numbers. The distinction between being solely a "quantitative person" or a "qualitative person" is increasingly outdated. Mastering both techniques will enhance your ability to analyse and interpret diverse datasets, depending on the research question and project goals, making you a more versatile and practical analyst.

The course uses Excel, as we have identified a gap in training students to use Excel, despite it being a primary tool for data analysis (whether we like it or not) in many public and private sector organisations. As many students take [Q-step internships](https://www.humanities.manchester.ac.uk/q-step/), this skill was identified as necessary. 

By the end of this module, you will have a strong foundation in various data types, the methods to generate them, and the approaches to analyse them. Engage actively with the materials, and consider how these techniques can be applied in real-world scenarios.

## Disclaimer {-}

Please beware that:

- In making these notes, while we briefly cover some concepts, students are expected to do the weekly reading, watch the pre-recorded videos and participate in lab discussions to receive a complete course experience. These notes are *not* intended to be a stand-alone reference or textbook but rather a set of exercises to gain hands-on practice with the concepts introduced during the course.
- These pages are the content of the BA Criminology 2nd year course, Making Sense of Criminological Data. They are meant to (very gently) introduce undergraduates to the concept of data analysis and cover descriptive statistics and the key concepts required to build an understanding of quantitative and qualitative data analysis in crime research. It is followed in the second term by Modelling Criminological Data, where students cover inferential statistics. The notes presented here are supported by compulsory reading, so they do not comprehensively describe these techniques and tools and how to use them.
The handouts below use, among other data sets, data from the [UK Data Service](https://ukdataservice.ac.uk/), such as the [Crime Survey for England and Wales](https://beta.ukdataservice.ac.uk/datacatalogue/series/series?id=200009), which is available under an Open Government Licence. This dataset is designed to be a learning resource and should not be used for research purposes or the production of summary statistics.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
options(tinytex.verbose = TRUE)
```


## Overview of course {-}

In this module, you will learn how to source, interpret, wrangle, analyse, visualise, and draw meaningful conclusions from data. Over the coming 10 weeks, you will build your knowledge and understanding of data analysis within the context of Criminological and broader Social Science research. We will cover quantitative and qualitative data analysis techniques, research design, and visualisations to give you a well-rounded and comprehensive introduction to the world of data in these domains. 

You should watch the introduction videos on Canvas for an overview of this course and for a guide on how to navigate this module. 

### Module structure {-}

This module's setup is different from your other lectures and seminar-based courses. This course is 10 weeks, and each week is made up of the following elements: 

1) Preparatory reading
2) Pre-recorded lecture videos
3) Lab session
4) Homework task
5) Homework quiz
6) Recap & Discussion session

Each element is described in detail below:

#### 1) Preparatory reading {-}

Each week, you will receive some preliminary reading or videos to watch before coming to the session. You should read these before coming to the lab session, because it will make engaging with the lab material easier for you.

The reading list can be found on the University of Manchester [Library Reading List  Online Services](https://www.library.manchester.ac.uk/services/teaching-services/reading-lists/), which you can access from Canvas as well.

#### 2) Pre-recorded lecture videos {-}

These short clips make up the lecture component of the module. They cover the key concepts you will learn each week, which you are also exposed to in your readings (Preparatory materials) and in your exercises (Lab session). We recommend watching these once before the lab and again after the lab session to really deepen your understanding. 

#### 3) Lab session {-}

Lab sessions are two-hour sessions held every week (except reading week - check your [personal university timetable](https://timetables.manchester.ac.uk/)) on campus. In these labs, you work together through the lab notes included in this book, and the teaching staff will be there to assist. Take the time to engage with these notes and ask the teaching team lots of questions. This is an opportunity to engage with the materials thoroughly. 

When you join a lesson, you will be able to get started straight away. You will find the instructions for each week in this booklet. You can open the link via Canvas and read the instructions chronologically. That means starting at the top and reading through to the bottom. 

Usually, within the notes, you will find some general introduction to the topic covered that week, with links to [videos](http://www.gapminder.org/videos/the-joy-of-stats/) or further [reading](http://flowingdata.com/2015/10/26/top-brewery-road-trip-routed-algorithmically/). You should come equipped with headphones to watch the videos. 

These lab notes also contain activities within them. You should do these activities in the lab and ask the teaching team for help when you are stuck or if you do not understand a concept. Even if everything goes smoothly and you do understand, if you want to clarify or ask further questions, please raise your hand during the session, and we will come to you. You can do this live in the sessions. You should come to these labs and engage to make sure you really follow the material. If you're unable to attend the lab sessions, you can ask questions on Canvas in the respective weeks. Please make lots of use of this. 

These activities will help you with your learning and contribute towards your post-lab task and homework quiz. You are welcome to talk with each other and with us, but please make sure that when it comes to understanding the learning behind these activities, you are confident in your ability. Again, we are happy for you to work together and help each other! The lab is here for you to engage with the activities, the teaching team, and each other. So do this! But also make sure you can independently make sense of what you have learned. The final essay will rely heavily on your ability to apply the concepts you learned during these activities and apply them in a way that shows your understanding.

#### 4) Homework task {-}

Each week, after completing the lab notes, you must complete some post-lab tasks in the form of a Homework task. These will take the form of a worksheet. You can find each worksheet and relevant material (e.g. data) on Canvas in the module for that week. You have to complete these tasks to be able to take the homework quiz **(which is assessed)**. The tasks will always mirror the in-lab activities, so if you get through those, the task should be a breeze. 

#### 5) Homework quiz {-}

Each week, you will have to complete a homework quiz. This quiz is assessed, and the average of your seven highest scores counts for 20% of your final mark (the other 80% is your final essay). The questions in the homework quiz will ask about key concepts from your reading, the lectures, and the answers to the homework task. Please make sure you have finished the task before you begin your homework quiz, and have it with you while doing so. The homework quiz will be available on Canvas and will be open as soon as the lab session is finished. It will then close again before the Recap & Discussion session (check Canvas for the exact timeframe). You can take the homework quiz any time between these times. You can take it only once. Once you activate the quiz, you will have only 30 minutes to complete it. Please make sure you are in a quiet environment where you will not be disturbed, with your reading notes and your post-lab task with you, so that you can complete the homework quiz successfully. After you submit it, you will receive immediate feedback. 

Don't forget your homework is graded and counts towards your final mark. But you get to practice completing the tasks with the activities in the lab. And if you have time left over, you can always complete these tasks here in the lab. No matter where you complete them, having the tasks done and with you when you take the quiz will increase your confidence in the homework quiz exercises. 


#### 6) Recap & Discussion session {-}

In this session, we will recap some key concepts from the week, review relevant work from the lab session, address some key questions from the discussion boards, and hold a Q&A session where you can ask questions about the lecture videos, labs, or homework tasks. We encourage you to bring your own examples to these sessions whenever you encounter them. If you're unable to attend these sessions, please post your questions on Canvas in the respective weeks. 



